import { Media } from "@src/entity/Media";
import { Connection, Edge } from "@src/entity/Connection";

/**
 * CategoryBreadcrumb - represents a single breadcrumb item
 */
export interface CategoryBreadcrumb {
  /** Global unique identifier */
  id: string;
  /** Category title */
  title: string;
  /** URL-friendly slug */
  handle: string;
}

/**
 * ListingType - defines the type of listing
 */
export enum ListingType {
  /** Automatically generated by applying predefined filters */
  SMART = "SMART",
  /** Manually curated: admin selects products and defines their order */
  STANDARD = "STANDARD",
  /** Aggregates all products from this category and its subcategories recursively */
  CONTAINER = "CONTAINER",
}

/**
 * Category - product category
 */
export interface Category {
  /** Global unique identifier */
  id: string;
  /** Category title */
  title: string;
  /** URL-friendly slug */
  handle: string;
  /** Full description of the category */
  description: string;
  /** Short excerpt or summary of the category */
  excerpt: string;
  /** Cover image for the category */
  cover?: Media;
  /** Breadcrumb trail from root to this category */
  breadcrumbs?: Array<CategoryBreadcrumb>;
  /** The listing mode for this category */
  listingType?: ListingType;
  /** DateTime when the category was created */
  createdAt: string;
  /** DateTime when the category was last updated */
  updatedAt: string;
  /** SEO title for the category page */
  seoTitle?: string;
  /** SEO description for the category page */
  seoDescription?: string;
}

/**
 * CategoryEdge - edge type for category connections
 */
export type CategoryEdge = Edge<Category>;

/**
 * CategoryConnection - paginated collection of categories
 */
export type CategoryConnection = Connection<Category>;
