import type { Entity } from '@shopana/entity';
import type { PageEntity } from '../types';

const PLACEHOLDER_IMAGE: Entity.Media = {
  id: 'placeholder_img',
  url: 'https://placehold.co/1200x600',
  source: 'placeholder',
};

const MOCK_MONEY: Entity.Money = {
  amount: 199,
  currencyCode: 'USD',
};

export function createMockProduct(handle: string): Entity.Product {
  const title = handle.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());

  const variant: Entity.ProductVariant = {
    id: `var_${handle}_default`,
    iid: '1',
    handle: `${handle}-default`,
    title: `${title} - Default`,
    description: 'Demo product variant generated by @shopana/next-ecommerce-core.',
    excerpt: 'Demo variant',
    selectedOptions: [],
    price: MOCK_MONEY,
    cover: PLACEHOLDER_IMAGE,
    stockStatus: { isAvailable: true },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  return {
    id: `prod_${handle}`,
    handle,
    title,
    description: 'Demo product generated by @shopana/next-ecommerce-core.',
    excerpt: 'Demo product',
    options: [],
    groups: [],
    features: [],
    rating: {
      id: 'rating_demo',
      rating: 4.5,
      count: 10,
      breakdown: [],
    },
    tags: {
      edges: [
        {
          node: {
            id: 'tag_demo',
            title: 'demo',
            handle: 'demo',
          },
          cursor: 'demo',
        },
      ],
      pageInfo: {
        hasNextPage: false,
        hasPreviousPage: false,
        startCursor: 'demo',
        endCursor: 'demo',
      },
      totalCount: 1,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [variant],
  };
}

export function createMockCollection(handle: string): Entity.Category {
  return {
    id: `cat_${handle}`,
    handle,
    title: `${handle} Collection`,
    description: 'Demo collection generated by @shopana/next-ecommerce-core.',
    excerpt: 'Demo collection',
    cover: PLACEHOLDER_IMAGE,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

export function createMockPage(handle: string): PageEntity {
  return {
    id: `page_${handle}`,
    handle,
    title: handle.replace(/-/g, ' '),
    body: 'Demo page body generated by @shopana/next-ecommerce-core.',
  };
}

export function createMockCart(): Entity.Cart {
  const variant: Entity.ProductVariant = {
    id: 'var_demo',
    iid: '1',
    handle: 'demo-product',
    title: 'Demo Product',
    description: 'Demo product for cart',
    excerpt: 'Demo',
    selectedOptions: [],
    price: MOCK_MONEY,
    stockStatus: { isAvailable: true },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  return {
    id: 'cart_demo',
    createdAt: new Date(),
    updatedAt: new Date(),
    totalQuantity: 1,
    cost: {
      subtotalAmount: MOCK_MONEY,
      totalAmount: MOCK_MONEY,
      totalDiscountAmount: null,
      totalTaxAmount: null,
      totalShippingAmount: null,
    },
    lines: [
      {
        id: 'line_1',
        quantity: 1,
        purchasableId: 'var_demo',
        purchasable: variant,
        cost: {
          unitPrice: MOCK_MONEY,
          compareAtUnitPrice: null,
          subtotalAmount: MOCK_MONEY,
          totalAmount: MOCK_MONEY,
        },
      },
    ],
  };
}
