import type {
  CartEntity,
  CollectionEntity,
  PageEntity,
  ProductEntity,
} from '../../core/entities';

const PLACEHOLDER_IMAGE = {
  url: 'https://placehold.co/1200x600',
  alt: 'Placeholder image',
  width: 1200,
  height: 600,
};

export function createMockProduct(handle: string): ProductEntity {
  return {
    id: `prod_${handle}`,
    handle,
    title: handle.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
    description: 'Demo product generated by @shopana/next-ecommerce-core.',
    price: 199,
    currencyCode: 'USD',
    availableForSale: true,
    images: [PLACEHOLDER_IMAGE],
    tags: ['demo'],
  };
}

export function createMockCollection(handle: string): CollectionEntity {
  return {
    id: `col_${handle}`,
    handle,
    title: `${handle} Collection`,
    description: 'Demo collection generated by @shopana/next-ecommerce-core.',
    image: PLACEHOLDER_IMAGE,
  };
}

export function createMockPage(handle: string): PageEntity {
  return {
    id: `page_${handle}`,
    handle,
    title: handle.replace(/-/g, ' '),
    body: 'Demo page body generated by @shopana/next-ecommerce-core.',
  };
}

export function createMockCart(): CartEntity {
  return {
    id: 'cart_demo',
    lines: [
      {
        id: 'line_1',
        title: 'Demo Line Item',
        quantity: 1,
        price: 199,
        currencyCode: 'USD',
        productId: 'prod_demo',
      },
    ],
    subtotal: 199,
    total: 199,
    currencyCode: 'USD',
  };
}
